### ISSUE TITLE
Styling of pages is broken

### ISSUE THREAD

**Issue by Nagelfar** [Softwarepark/Contexture#77]
After merging #76 pages seem to be broken:
Mostly some styles are missing (e.g. badges are white text on white background) and the spacing between components is wrong.

Maybe it's because we are still using plain bootstrap styles instead of 'the new styles' in the frontend?
What can we do for a gradual migration of the styles?

**Comment by alkstal** [comment]
What #76 did was remove the duplicate application of Bootstrap.
Whatever Bootstrap configuration we had was mostly overridden by the second application of Bootstrap from the CDN. There was a conflict between the two and the CDN version mostly won because it was applied later.

By removing the Bootstrap styles applied from the CDN version, we actually got the styles as we had configured them.
What we see now is 100% our custom Bootstrap configuration.

I see some further issues now though. One is that we might not have configured enough of Bootstrap for our needs because the previous conflict obscured that to us.
And another is that ElmBootstrap components are applying CSS classes that don't exist anymore in Bootstrap 5.
This is the reason why some texts are white on white background, because ElmBootstrap is using a CSS class used in version 4 that has changed in version 5.

"What can we do for a gradual migration of the styles?"

We could revert #76 from `master` and wait to reapply changes until all changes are done?

I find it problematic that ElmBootstrap is built for version 4 and not 5 and I don't think using hacks to work around that is a good way to go.

Removing ElmBootstrap is also a bit of work, because that requires us to build the HTML structure and use the correct CSS classes ourselves and that takes a bit of learning time (at least for me) to check Bootstrap docs on how things should be put together and then learn how to do it using Elm.

Learning _The Elm Way_ of doing things is going to add development time as it's a change from how you usually work with JavaScript.
